apiVersion: v1
kind: Pod
metadata:
  name: ansible-pod
spec:
  containers:
  - name: ansible
    image: ansible/ansible
    command: ["/bin/sh"]
    args: ["-c", "sleep infinity"]
    volumeMounts:
      - mountPath: "/home/ansible"
        name: ansible-playbooks-volume
volumes:
    - name: ansible-playbooks-volume
      persistentVolumeClaim:
        claimName: task-pv-claim