apiVersion: v1
kind: PersistentVolume
metadata:
  name: ansible-playbooks-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path:  /TODO